import Layout from "@/components/Layout";
import { LegalPage, LegalIntro, LegalSection, LegalList } from "@/components/LegalPage";

const TermsAndConditions = () => (
  <LegalPage title="Terms and Conditions" updated="15-01-2026">
    <LegalIntro>
      <p>At Forte Digital Solutions LLP, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by our platform and how we use it.</p>
      <p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>
      <p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect on our platform.</p>
    </LegalIntro>

    <LegalSection title="Consent">
      <p>By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>
    </LegalSection>

    <LegalSection title="Information We Collect">
      <p>The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information.</p>
      <p className="mt-2">If you contact us directly, we may receive additional information about you such as your name, email address, phone number, and any other information you may choose to provide.</p>
      <p className="mt-2">When you register for an Account, we may ask for your contact information, including name, company name, address, email address, and telephone number.</p>
    </LegalSection>

    <LegalSection title="How We Use Your Information">
      <LegalList
        items={[
          "Provide, operate, and maintain our website",
          "Improve, personalize, and expand our website",
          "Understand and analyze how you use our website",
          "Develop new astrology products, services, features, and functionality",
          "Communicate with you, including for customer service, updates, and promotional purposes",
          "Send you emails",
          "Find and prevent fraud",
        ]}
      />
    </LegalSection>

    <LegalSection title="Log Files">
      <p>Our platform follows a standard procedure of using log files. The information collected includes IP addresses, browser type, ISP, date and time stamp, referring/exit pages. These are not linked to any personally identifiable information.</p>
    </LegalSection>

    <LegalSection title="Cookies and Web Beacons">
      <p>Like any other website, our platform uses &apos;cookies&apos; to store information including visitors&apos; preferences and the pages on the website that the visitor accessed. The information is used to optimize users&apos; experience by customizing our web page content based on visitors&apos; browser type and/or other information.</p>
    </LegalSection>

    <LegalSection title="CCPA Privacy Rights">
      <LegalList
        items={[
          "Request that a business disclose the categories and specific pieces of personal data collected about consumers.",
          "Request that a business delete any personal data about the consumer that a business has collected.",
          "Request that a business that sells a consumer's personal data, not sell the consumer's personal data.",
        ]}
      />
      <p className="mt-3">If you make a request, we have one month to respond. Please contact us to exercise any of these rights.</p>
    </LegalSection>

    <LegalSection title="GDPR Data Protection Rights">
      <LegalList
        items={[
          "The right to access — You have the right to request copies of your personal data.",
          "The right to rectification — You have the right to request that we correct inaccurate information.",
          "The right to erasure — You have the right to request that we erase your personal data, under certain conditions.",
          "The right to restrict processing — You have the right to request that we restrict the processing of your personal data.",
          "The right to object to processing — You have the right to object to our processing of your personal data.",
          "The right to data portability — You have the right to request that we transfer the data that we have collected to another organization, or directly to you.",
        ]}
      />
    </LegalSection>

    <LegalSection title="Terms and Conditions">
      {[
        { l: "A.", t: "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures." },
        { l: "B.", t: "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of our platform." },
        { l: "C.", t: 'The Platform is owned by Forte Digital Solutions LLP, a company incorporated under the Companies Act, 1956 (hereinafter referred to as "Platform Owner", "we", "us", "our").' },
        { l: "D.", t: "Your use of the Platform and services and tools are governed by the following Terms of Use as applicable to the Platform including the applicable policies which are incorporated herein by way of reference." },
        { l: "E.", t: 'For the purpose of these Terms of Use, "you", "your" or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.' },
        { l: "F.", t: "ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ CAREFULLY BEFORE PROCEEDING." },
      ].map(({ l, t }) => (
        <div key={l} className="flex gap-3 mb-4 last:mb-0">
          <span className="text-amber-400 font-semibold shrink-0">{l}</span>
          <p>{t}</p>
        </div>
      ))}
    </LegalSection>
  </LegalPage>
);

export default TermsAndConditions;
